apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/social-archive/argo_test.git
    targetRevision: HEAD
    path: .
    directory:
      include: '{deployment.yaml,service.yaml,springboot-deployment.yaml,springboot-service.yaml}'
      exclude: 'application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: github-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true