apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-developer
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081  # http://localhost:8081 으로 접근 가능
    protocol: TCP
    name: http
  selector:
    app: springboot-developer
