apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: springboot-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAic29jaWFsLWFyY2hpdmUiLAogICAgICAicGFzc3dvcmQiOiAiZ2hwX3d4U1ZYS1JJaDJQRXJXR0tSdzVBUE02a1FtM2l0bTNVWVp6ZyIsCiAgICAgICJhdXRoIjogImMyOWphV0ZzTFdGeVkyaHBkbVU2WjJod1gzZDRVMVpZUzFKSmFESndSWEpYUjB0U2R6VkJVRTEyYTFGdE0ybDBiVE5WV1ZwNlp3PT0iCiAgICB9CiAgfQp9
